//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobInTown.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobInTown.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t obtain valid addresses..
        /// </summary>
        internal static string AddItemPage_AddressError_Exception_Message {
            get {
                return ResourceManager.GetString("AddItemPage_AddressError_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string AddItemPage_Category_Label_Text {
            get {
                return ResourceManager.GetString("AddItemPage_Category_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string AddItemPage_Contract_Label_Text {
            get {
                return ResourceManager.GetString("AddItemPage_Contract_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string AddItemPage_Description_Label_Text {
            get {
                return ResourceManager.GetString("AddItemPage_Description_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not valid. Please try another address..
        /// </summary>
        internal static string AddItemPage_InvalidAdress_Exception_Message {
            get {
                return ResourceManager.GetString("AddItemPage_InvalidAdress_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file is invalid. Try with .png or .jpg image..
        /// </summary>
        internal static string AddItemPage_InvalidImage_Exception_Message {
            get {
                return ResourceManager.GetString("AddItemPage_InvalidImage_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string AddItemPage_Location_Label_Text {
            get {
                return ResourceManager.GetString("AddItemPage_Location_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get location. Check your configuration and try again later..
        /// </summary>
        internal static string AddItemPage_LocationError_Exception_Message {
            get {
                return ResourceManager.GetString("AddItemPage_LocationError_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add a description..
        /// </summary>
        internal static string AddItemPage_NoDescription_Exception_Message {
            get {
                return ResourceManager.GetString("AddItemPage_NoDescription_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add a location..
        /// </summary>
        internal static string AddItemPage_NoLocation_Exception_Message {
            get {
                return ResourceManager.GetString("AddItemPage_NoLocation_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add a title..
        /// </summary>
        internal static string AddItemPage_NoTitle_Exception_Message {
            get {
                return ResourceManager.GetString("AddItemPage_NoTitle_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new job.
        /// </summary>
        internal static string AddItemPage_Page_Title {
            get {
                return ResourceManager.GetString("AddItemPage_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the photo?.
        /// </summary>
        internal static string AddItemPage_RemoveImage_Confirmation_Message {
            get {
                return ResourceManager.GetString("AddItemPage_RemoveImage_Confirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AddItemPage_Save_ToolBarItem_Text {
            get {
                return ResourceManager.GetString("AddItemPage_Save_ToolBarItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string AddItemPage_Title_Label_Text {
            get {
                return ResourceManager.GetString("AddItemPage_Title_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workday.
        /// </summary>
        internal static string AddItemPage_Workday_Label_Text {
            get {
                return ResourceManager.GetString("AddItemPage_Workday_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        internal static string Android_ItemDetailPage_Information_ContentPage_Title {
            get {
                return ResourceManager.GetString("Android_ItemDetailPage_Information_ContentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        internal static string Android_ItemDetailPage_Map_ContentPage_Title {
            get {
                return ResourceManager.GetString("Android_ItemDetailPage_Map_ContentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string Android_MainPage_Jobs_ContentPage_Title {
            get {
                return ResourceManager.GetString("Android_MainPage_Jobs_ContentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE.
        /// </summary>
        internal static string Android_MainPage_Profile_ContentPage_Title {
            get {
                return ResourceManager.GetString("Android_MainPage_Profile_ContentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration &amp; Secretariat.
        /// </summary>
        internal static string Enum_CategoryType_AdministrationSecretariat {
            get {
                return ResourceManager.GetString("Enum_CategoryType_AdministrationSecretariat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art &amp; Design.
        /// </summary>
        internal static string Enum_CategoryType_ArtDesign {
            get {
                return ResourceManager.GetString("Enum_CategoryType_ArtDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking, Finance &amp; Insurance.
        /// </summary>
        internal static string Enum_CategoryType_BankingFinanceInsurance {
            get {
                return ResourceManager.GetString("Enum_CategoryType_BankingFinanceInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Management.
        /// </summary>
        internal static string Enum_CategoryType_BusinessManagement {
            get {
                return ResourceManager.GetString("Enum_CategoryType_BusinessManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction &amp; Real state.
        /// </summary>
        internal static string Enum_CategoryType_ConstructionRealState {
            get {
                return ResourceManager.GetString("Enum_CategoryType_ConstructionRealState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education, Formation &amp; Investigation.
        /// </summary>
        internal static string Enum_CategoryType_EducationTrainingResearch {
            get {
                return ResourceManager.GetString("Enum_CategoryType_EducationTrainingResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering &amp; Production.
        /// </summary>
        internal static string Enum_CategoryType_EngineeringProduction {
            get {
                return ResourceManager.GetString("Enum_CategoryType_EngineeringProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health &amp; Social Services.
        /// </summary>
        internal static string Enum_CategoryType_HealthSocialServices {
            get {
                return ResourceManager.GetString("Enum_CategoryType_HealthSocialServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home services.
        /// </summary>
        internal static string Enum_CategoryType_HomeServices {
            get {
                return ResourceManager.GetString("Enum_CategoryType_HomeServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostel &amp; Tourism.
        /// </summary>
        internal static string Enum_CategoryType_HostelTourism {
            get {
                return ResourceManager.GetString("Enum_CategoryType_HostelTourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resources.
        /// </summary>
        internal static string Enum_CategoryType_HumanResources {
            get {
                return ResourceManager.GetString("Enum_CategoryType_HumanResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        internal static string Enum_CategoryType_Legal {
            get {
                return ResourceManager.GetString("Enum_CategoryType_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics &amp; Transport.
        /// </summary>
        internal static string Enum_CategoryType_LogisticsTransportation {
            get {
                return ResourceManager.GetString("Enum_CategoryType_LogisticsTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing &amp; Comunication.
        /// </summary>
        internal static string Enum_CategoryType_MarketingCommunication {
            get {
                return ResourceManager.GetString("Enum_CategoryType_MarketingCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string Enum_CategoryType_Others {
            get {
                return ResourceManager.GetString("Enum_CategoryType_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional crafts.
        /// </summary>
        internal static string Enum_CategoryType_ProfessionalCrafts {
            get {
                return ResourceManager.GetString("Enum_CategoryType_ProfessionalCrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality &amp; I+D.
        /// </summary>
        internal static string Enum_CategoryType_QualityID {
            get {
                return ResourceManager.GetString("Enum_CategoryType_QualityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnology &amp; Informatics.
        /// </summary>
        internal static string Enum_CategoryType_TechnologyInformatics {
            get {
                return ResourceManager.GetString("Enum_CategoryType_TechnologyInformatics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade &amp; Sales.
        /// </summary>
        internal static string Enum_CategoryType_TradeSales {
            get {
                return ResourceManager.GetString("Enum_CategoryType_TradeSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed discontinuous.
        /// </summary>
        internal static string Enum_ContractType_FixedDiscontinuous {
            get {
                return ResourceManager.GetString("Enum_ContractType_FixedDiscontinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed term.
        /// </summary>
        internal static string Enum_ContractType_FixedTerm {
            get {
                return ResourceManager.GetString("Enum_ContractType_FixedTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formative.
        /// </summary>
        internal static string Enum_ContractType_Formative {
            get {
                return ResourceManager.GetString("Enum_ContractType_Formative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freelance.
        /// </summary>
        internal static string Enum_ContractType_Freelance {
            get {
                return ResourceManager.GetString("Enum_ContractType_Freelance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indefinite.
        /// </summary>
        internal static string Enum_ContractType_Indefinite {
            get {
                return ResourceManager.GetString("Enum_ContractType_Indefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Enum_ContractType_Other {
            get {
                return ResourceManager.GetString("Enum_ContractType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part time.
        /// </summary>
        internal static string Enum_ContractType_PartTime {
            get {
                return ResourceManager.GetString("Enum_ContractType_PartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relief.
        /// </summary>
        internal static string Enum_ContractType_Relief {
            get {
                return ResourceManager.GetString("Enum_ContractType_Relief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string Enum_DateTimeDiffFormatType_Day {
            get {
                return ResourceManager.GetString("Enum_DateTimeDiffFormatType_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Enum_DateTimeDiffFormatType_Days {
            get {
                return ResourceManager.GetString("Enum_DateTimeDiffFormatType_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string Enum_DateTimeDiffFormatType_Hour {
            get {
                return ResourceManager.GetString("Enum_DateTimeDiffFormatType_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Enum_DateTimeDiffFormatType_Hours {
            get {
                return ResourceManager.GetString("Enum_DateTimeDiffFormatType_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string Enum_DateTimeDiffFormatType_Minute {
            get {
                return ResourceManager.GetString("Enum_DateTimeDiffFormatType_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Enum_DateTimeDiffFormatType_Minutes {
            get {
                return ResourceManager.GetString("Enum_DateTimeDiffFormatType_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string Enum_DateTimeDiffFormatType_Month {
            get {
                return ResourceManager.GetString("Enum_DateTimeDiffFormatType_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string Enum_DateTimeDiffFormatType_Months {
            get {
                return ResourceManager.GetString("Enum_DateTimeDiffFormatType_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string Enum_DateTimeDiffFormatType_Second {
            get {
                return ResourceManager.GetString("Enum_DateTimeDiffFormatType_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Enum_DateTimeDiffFormatType_Seconds {
            get {
                return ResourceManager.GetString("Enum_DateTimeDiffFormatType_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string Enum_DateTimeDiffFormatType_Year {
            get {
                return ResourceManager.GetString("Enum_DateTimeDiffFormatType_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string Enum_DateTimeDiffFormatType_Years {
            get {
                return ResourceManager.GetString("Enum_DateTimeDiffFormatType_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full time.
        /// </summary>
        internal static string Enum_WorkdayType_FullTime {
            get {
                return ResourceManager.GetString("Enum_WorkdayType_FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indifferent.
        /// </summary>
        internal static string Enum_WorkdayType_Indifferent {
            get {
                return ResourceManager.GetString("Enum_WorkdayType_Indifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensive - Afternoon.
        /// </summary>
        internal static string Enum_WorkdayType_IntensiveAfternoon {
            get {
                return ResourceManager.GetString("Enum_WorkdayType_IntensiveAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensive - Indifferent.
        /// </summary>
        internal static string Enum_WorkdayType_IntensiveIndifferent {
            get {
                return ResourceManager.GetString("Enum_WorkdayType_IntensiveIndifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensive - Morning.
        /// </summary>
        internal static string Enum_WorkdayType_IntensiveMorning {
            get {
                return ResourceManager.GetString("Enum_WorkdayType_IntensiveMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensive - Night.
        /// </summary>
        internal static string Enum_WorkdayType_IntensiveNight {
            get {
                return ResourceManager.GetString("Enum_WorkdayType_IntensiveNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Enum_WorkdayType_Other {
            get {
                return ResourceManager.GetString("Enum_WorkdayType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial - Afternoon.
        /// </summary>
        internal static string Enum_WorkdayType_PartialAfternoon {
            get {
                return ResourceManager.GetString("Enum_WorkdayType_PartialAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial - Infifferent.
        /// </summary>
        internal static string Enum_WorkdayType_PartialIndifferent {
            get {
                return ResourceManager.GetString("Enum_WorkdayType_PartialIndifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial - Morning.
        /// </summary>
        internal static string Enum_WorkdayType_PartialMorning {
            get {
                return ResourceManager.GetString("Enum_WorkdayType_PartialMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial - Night.
        /// </summary>
        internal static string Enum_WorkdayType_PartialNight {
            get {
                return ResourceManager.GetString("Enum_WorkdayType_PartialNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something goes wrong. Try again later..
        /// </summary>
        internal static string Exception_General_Message {
            get {
                return ResourceManager.GetString("Exception_General_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string iOS_ItemDetailPage_Information_ContentPage_Title {
            get {
                return ResourceManager.GetString("iOS_ItemDetailPage_Information_ContentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string iOS_ItemDetailPage_Map_ContentPage_Title {
            get {
                return ResourceManager.GetString("iOS_ItemDetailPage_Map_ContentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string iOS_MainPage_Jobs_ContentPage_Title {
            get {
                return ResourceManager.GetString("iOS_MainPage_Jobs_ContentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string iOS_MainPage_Profile_ContentPage_Title {
            get {
                return ResourceManager.GetString("iOS_MainPage_Profile_ContentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ItemDetailPage_Delete_ToolBarItem_Text {
            get {
                return ResourceManager.GetString("ItemDetailPage_Delete_ToolBarItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about {0:N2}km. from:.
        /// </summary>
        internal static string ItemDetailPage_Distance_Kilometers_Text {
            get {
                return ResourceManager.GetString("ItemDetailPage_Distance_Kilometers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about {0:N2}m. from:.
        /// </summary>
        internal static string ItemDetailPage_Distance_Meters_Text {
            get {
                return ResourceManager.GetString("ItemDetailPage_Distance_Meters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get location. Check your configuration and try again later..
        /// </summary>
        internal static string ItemDetailPage_LocationError_Exception_Message {
            get {
                return ResourceManager.GetString("ItemDetailPage_LocationError_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job detail.
        /// </summary>
        internal static string ItemDetailPage_Page_Title {
            get {
                return ResourceManager.GetString("ItemDetailPage_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this job?.
        /// </summary>
        internal static string ItemDetailPage_RemoveJob_Confirmation_Message {
            get {
                return ResourceManager.GetString("ItemDetailPage_RemoveJob_Confirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted on {0:dd MMMM yyyy} ({1} ago).
        /// </summary>
        internal static string Job_PostedDate_Text {
            get {
                return ResourceManager.GetString("Job_PostedDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginPage_Email_Label_Text {
            get {
                return ResourceManager.GetString("LoginPage_Email_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LoginPage_Login_Button_Text {
            get {
                return ResourceManager.GetString("LoginPage_Login_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPage_Password_Label_Text {
            get {
                return ResourceManager.GetString("LoginPage_Password_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string LoginPage_Register_Button_Text {
            get {
                return ResourceManager.GetString("LoginPage_Register_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string LoginPage_Register_Label_Text {
            get {
                return ResourceManager.GetString("LoginPage_Register_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string MainPage_Add_ToolBarItem_Text {
            get {
                return ResourceManager.GetString("MainPage_Add_ToolBarItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order - Date.
        /// </summary>
        internal static string MainPage_DateOrder_ToolBarItem_Text {
            get {
                return ResourceManager.GetString("MainPage_DateOrder_ToolBarItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order - Distance.
        /// </summary>
        internal static string MainPage_DistanceOrder_ToolBarItem_Text {
            get {
                return ResourceManager.GetString("MainPage_DistanceOrder_ToolBarItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MainPage_Logout_Button_Text {
            get {
                return ResourceManager.GetString("MainPage_Logout_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not yet created any jobs, try to create a new one..
        /// </summary>
        internal static string MainPage_MyJobsList_NoItems_Label_Text {
            get {
                return ResourceManager.GetString("MainPage_MyJobsList_NoItems_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order - Name.
        /// </summary>
        internal static string MainPage_NameOrder_ToolBarItem_Text {
            get {
                return ResourceManager.GetString("MainPage_NameOrder_ToolBarItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string MainPage_Refresh_ToolBarItem_Text {
            get {
                return ResourceManager.GetString("MainPage_Refresh_ToolBarItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string RegisterPage_ConfirmPassword_Label_Text {
            get {
                return ResourceManager.GetString("RegisterPage_ConfirmPassword_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string RegisterPage_Email_Label_Text {
            get {
                return ResourceManager.GetString("RegisterPage_Email_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string RegisterPage_FullName_Label_Text {
            get {
                return ResourceManager.GetString("RegisterPage_FullName_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterPage_Page_Title {
            get {
                return ResourceManager.GetString("RegisterPage_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegisterPage_Password_Label_Text {
            get {
                return ResourceManager.GetString("RegisterPage_Password_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterPage_Register_ToolBarItem_Text {
            get {
                return ResourceManager.GetString("RegisterPage_Register_ToolBarItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}, welcome to JobInTown..
        /// </summary>
        internal static string RegisterPage_Welcome_Message {
            get {
                return ResourceManager.GetString("RegisterPage_Welcome_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Windows_ItemDetailPage_Information_ContentPage_Title {
            get {
                return ResourceManager.GetString("Windows_ItemDetailPage_Information_ContentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Windows_ItemDetailPage_Map_ContentPage_Title {
            get {
                return ResourceManager.GetString("Windows_ItemDetailPage_Map_ContentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Windows_MainPage_Jobs_ContentPage_Title {
            get {
                return ResourceManager.GetString("Windows_MainPage_Jobs_ContentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Windows_MainPage_Profile_ContentPage_Title {
            get {
                return ResourceManager.GetString("Windows_MainPage_Profile_ContentPage_Title", resourceCulture);
            }
        }
    }
}
